// Localization data for BhuMitra app
const Map<String, Map<String, String>> translations = {
  'en': {
    // App & Navigation
    'app_name': 'BhuMitra',
    'welcome_back': 'Welcome Back,',
    'farmer': 'Farmer',
    'home': 'Home',
    'profile': 'Profile',
    'settings': 'Settings',
    'help': 'Help',
    'help_support': 'Help & Support',
    'send_feedback': 'Send Feedback',
    'about': 'About BhuMitra',
    'logout': 'Logout',
    'select_language': 'Select Language',

    // Common Actions
    'save': 'Save',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'view': 'View',
    'share': 'Share',
    'reset': 'Reset',
    'calculate': 'Calculate',
    'continue': 'Continue',
    'skip': 'Skip',
    'get_started': 'Get Started',
    'try_again': 'Try Again',
    'open_settings': 'Open Settings',
    'undo': 'Undo',
    'finish': 'Finish',

    // Quick Actions
    'saved_plots': 'Saved Plots',
    'unit_converter': 'Unit Converter',
    'recent': 'Recent',
    'quick_actions': 'Quick Actions',

    // Measurement
    'start_measuring': 'Start Measuring',
    'measure_now': 'Measure Now',
    'measure_land': 'Measure Land',
    'measure_new_land': 'Measure New Land',
    'mark_boundaries': 'Mark Boundaries',
    'points_marked': 'Points Marked',
    'mark_point': 'Mark Point',

    // Settings
    'general_settings': 'General Settings',
    'dark_mode': 'Dark Mode',
    'dark_mode_desc': 'Enable dark theme',
    'map_settings': 'Map Settings',
    'map_type': 'Map Type',
    'default_unit': 'Default Unit',
    'measurement_settings': 'Measurement Settings',
    'precision_level': 'Precision Level',
    'reset_defaults': 'Reset to Defaults',
    'reset_settings': 'Reset Settings',
    'settings_reset': 'Settings reset to defaults',
    'reset_settings_confirm':
        'Are you sure you want to reset all settings to defaults?',

    // Map Types
    'normal': 'Normal',
    'satellite': 'Satellite',
    'terrain': 'Terrain',
    'hybrid': 'Hybrid',

    // Profile
    'edit_profile': 'Edit Profile',
    'update_profile': 'Update Profile',
    'personal_info': 'Personal Information',
    'name': 'Name',
    'email': 'Email',
    'phone': 'Phone',
    'location': 'Location',
    'statistics': 'Statistics',
    'plots_saved': 'Plots Saved',
    'measurements': 'Measurements',
    'profile_updated': 'Profile updated successfully',

    // Area Result
    'area_calculation_result': 'Area Calculation Result',
    'area_measurements': 'Area Measurements',
    'custom_local_unit': 'Custom Local Unit',
    'unit_name': 'Unit Name',
    'unit_name_hint': 'e.g., Bigha, Katha, Guntha',
    'conversion_value': 'Conversion Value',
    'value_hint': 'Value',
    'base_unit': 'Base Unit',
    'area': 'Area',
    'unit': 'Unit',
    'value': 'Value',

    // Saved Plots
    'save_plot': 'Save Plot',
    'plot_name': 'Plot Name',
    'plot_name_hint': 'e.g., North Field',
    'no_saved_plots': 'No Saved Plots Yet',
    'no_plots_found': 'No Plots Found',
    'no_plot_with_name': 'No saved plot with name',
    'try_different_search': 'Try searching with a different name or location',
    'start_measuring_land':
        'Start measuring your land to save plots and access them anytime',
    'search_by_name_location': 'Search by name or location...',
    'delete_plot': 'Delete Plot',
    'delete_plot_confirm': 'Are you sure you want to delete this plot?',
    'delete_plot_message': 'This action cannot be undone.',

    // PDF & Sharing
    'generating_pdf': 'Generating PDF...',
    'pdf_generated': 'PDF generated successfully',
    'pdf_shared': 'PDF shared successfully',
    'error_generating_pdf': 'Error generating PDF',
    'error_sharing_pdf': 'Error sharing PDF',
    'land_measurement_report': 'Land Measurement Report',
    'plot_report_for': 'Land measurement report for',
    'share_message': 'Here is the land measurement report from BhuMitra.',
    'generated_by': 'Generated by BhuMitra - Land Area Measurement App',
    'no_map_data': 'No map data available',
    'boundary_coordinates': 'Boundary Coordinates',
    'point': 'Point',
    'latitude': 'Latitude',
    'longitude': 'Longitude',
    'date': 'Date',
    'land_boundary_map': 'Land Boundary Map',
    'continued_next_page': 'Continued on next page...',

    // Messages & Notifications
    'saving_plot': 'Saving plot...',
    'plot_saved': 'Plot saved successfully',
    'error_saving_plot': 'Error saving plot',
    'custom_unit_saved': 'Custom unit saved',
    'fill_all_fields': 'Please fill in all fields',
    'enter_valid_number': 'Please enter a valid number',
    'minimum_points_required': 'Mark at least 3 points to calculate area',
    'calculating_area': 'Calculating area...',

    // Location & Permissions
    'gps_accuracy': 'GPS Accuracy',
    'high': 'High',
    'location_services_disabled': 'Location Services Disabled',
    'enable_location_services':
        'Please enable location services to use GPS features.',
    'location_permission_required': 'Location Permission Required',
    'location_permission_message':
        'This app needs location permission to mark land boundaries. Please grant permission to continue.',
    'location_permission_denied':
        'Location permission denied. Please enable it in settings to use this feature.',

    // Unit Converter
    'from': 'From',
    'to': 'To',
    'enter_value': 'Enter value',
    'result': 'Result',
    'conversion_info': 'Enter a value and select units to convert',

    // Help & Support
    'faqs': 'Frequently Asked Questions',
    'video_tutorials': 'Video Tutorials',
    'contact_support': 'Contact Support',
    'watch_tutorial': 'Watch Tutorial',

    // Auth
    'welcome_to': 'Welcome to',
    'login': 'Login',
    'register': 'Register',
    'email_address': 'Email Address',
    'password': 'Password',
    'confirm_password': 'Confirm Password',
    'forgot_password': 'Forgot Password?',
    'dont_have_account': "Don't have an account?",
    'already_have_account': 'Already have an account?',
    'sign_in_with_google': 'Sign in with Google',
    'or': 'OR',

    // About Screen
    'version': 'Version',
    'features': 'Features',
    'about_description':
        'BhuMitra is a comprehensive land measurement application designed to help farmers and land surveyors accurately measure land areas using GPS technology.',
    'gps_measurement': 'GPS-based land measurement',
    'save_manage_plots': 'Save and manage multiple plots',
    'multi_language': 'Multi-language support',
    'offline_mode_feature': 'Offline mode',
    'dark_mode_feature': 'Dark mode',
    'copyright': '© 2024 BhuMitra. All rights reserved.',

    // Help & Support Screen
    'help_us_improve': 'Help us improve',
    'view_user_guide': 'View Complete User Guide',
    'how_to_use_bhumitra': 'How to Use BhuMitra',
    'watch_step_by_step':
        'Watch our step-by-step guide to measuring land accurately',

    // FAQ Questions
    'faq_mark_boundaries_q': 'How to mark land boundaries?',
    'faq_mark_boundaries_a':
        'You can mark boundaries using two modes:\n\n• Pin Mode: Tap on the map to place markers at each corner\n• Walk Mode: Walk around your land with GPS tracking',
    'faq_area_units_q': 'Understanding area units',
    'faq_area_units_a':
        'BhuMitra supports multiple units:\n\n• Square Feet (sq ft)\n• Square Meters (sq m)\n• Square Yards (sq yd)\n• Acre\n• Hectare\n\nYou can also define custom local units like Bigha, Katha, Guntha.',
    'faq_save_measurements_q': 'How to save measurements?',
    'faq_save_measurements_a':
        'After calculating the area:\n\n1. Click the "Save Plot" button\n2. Enter a name for your plot\n3. Access saved plots from the home screen\n\nAll measurements are saved locally on your device.',
    'faq_gps_accuracy_q': 'GPS accuracy tips',
    'faq_gps_accuracy_a':
        'For better GPS accuracy:\n\n• Ensure location services are enabled\n• Use the app in open areas\n• Walk slowly around the boundary\n• Avoid tall buildings or dense tree cover\n• Wait for GPS signal to stabilize',
    'faq_custom_units_q': 'Using custom local units',
    'faq_custom_units_a':
        'To define custom units:\n\n1. Go to the Result Screen after measurement\n2. Find the "Custom Local Unit" section\n3. Enter your unit name (e.g., Bigha)\n4. Enter conversion factor\n5. Select base unit\n6. Click Calculate',
    'faq_offline_mode_q': 'Offline mode',
    'faq_offline_mode_a':
        'BhuMitra can work offline:\n\n• Enable offline mode in Settings\n• Maps will be cached for offline use\n• All measurements work without internet\n• Data syncs when online',

    // User Guide Screen
    'user_guide': 'User Guide',
    'introduction': 'Introduction',
    'introduction_desc':
        'BhuMitra is a powerful land measurement tool that uses GPS technology to help you accurately measure land areas. Whether you\'re a farmer, surveyor, or land owner, this app makes measuring land simple and precise.',
    'getting_started': 'Getting Started',
    'getting_started_desc':
        'Before you begin measuring, ensure your device has location services enabled and you have a clear view of the sky for better GPS accuracy. The app works best in open areas away from tall buildings.',
    'step_by_step_guide': 'Step-by-Step Guide',
    'step1_title': 'Open the App',
    'step1_desc':
        'Launch BhuMitra and grant location permissions when prompted. Wait for GPS signal to stabilize.',
    'step2_title': 'Start Measuring',
    'step2_desc':
        'Tap "Measure Land" from the home screen. Choose between Pin Mode (tap on map) or Walk Mode (walk around boundary).',
    'step3_title': 'Mark Boundaries',
    'step3_desc':
        'Mark at least 3 points around your land. In Walk Mode, walk slowly around the perimeter. In Pin Mode, tap each corner on the map.',
    'step4_title': 'Calculate Area',
    'step4_desc':
        'Once you\'ve marked all points, tap "Finish" to calculate the area. The app will show results in multiple units.',
    'step5_title': 'Save & Share',
    'step5_desc':
        'Save your measurement with a name for future reference. You can also generate and share PDF reports.',
    'tips_best_practices': 'Tips & Best Practices',
    'tips_desc':
        '• Always measure in open areas for best GPS accuracy\n• Walk slowly and steadily in Walk Mode\n• Mark points at exact corners in Pin Mode\n• Save measurements immediately after calculation\n• Use custom units for local measurements like Bigha or Katha',
    'troubleshooting': 'Troubleshooting',
    'troubleshooting_desc':
        'GPS not working? Check if location services are enabled in device settings.\n\nInaccurate measurements? Ensure you\'re in an open area and GPS signal is strong.\n\nApp crashing? Try restarting the app or clearing app cache.',

    // Connectivity
    'no_internet_connection': 'No internet connection',
    'internet_connected': 'Back online',
  },
  'hi': {
    // App & Navigation
    'app_name': 'BhuMitra',
    'welcome_back': 'वापसी पर स्वागत है,',
    'farmer': 'किसान',
    'home': 'होम',
    'profile': 'प्रोफ़ाइल',
    'settings': 'सेटिंग्स',
    'help': 'मदद',
    'help_support': 'मदद और सहायता',
    'send_feedback': 'प्रतिक्रिया भेजें',
    'about': 'भू-मित्र के बारे में',
    'logout': 'लॉग आउट',
    'select_language': 'भाषा चुनें',

    // Common Actions
    'save': 'सहेजें',
    'cancel': 'रद्द करें',
    'delete': 'हटाएं',
    'view': 'देखें',
    'share': 'साझा करें',
    'reset': 'रीसेट करें',
    'calculate': 'गणना करें',
    'continue': 'जारी रखें',
    'skip': 'छोड़ें',
    'get_started': 'शुरू करें',
    'try_again': 'पुनः प्रयास करें',
    'open_settings': 'सेटिंग्स खोलें',
    'undo': 'पूर्ववत करें',
    'finish': 'समाप्त करें',

    // Quick Actions
    'saved_plots': 'सहेजे गए भूखंड',
    'unit_converter': 'इकाई परिवर्तक',
    // 'recent': 'हाल ही का',
    'quick_actions': 'त्वरित कार्य',

    // Measurement
    'start_measuring': 'मापना शुरू करें',
    'measure_now': 'अभी मापें',
    'measure_land': 'भूमि मापें',
    'measure_new_land': 'नई भूमि मापें',
    'mark_boundaries': 'सीमाएं चिह्नित करें',
    'points_marked': 'बिंदु चिह्नित',
    'mark_point': 'बिंदु चिह्नित करें',

    // Settings
    'general_settings': 'सामान्य सेटिंग्स',
    'dark_mode': 'डार्क मोड',
    'dark_mode_desc': 'डार्क थीम सक्षम करें',
    'map_settings': 'मानचित्र सेटिंग्स',
    'map_type': 'मानचित्र प्रकार',
    'default_unit': 'डिफ़ॉल्ट इकाई',
    'measurement_settings': 'माप सेटिंग्स',
    'precision_level': 'सटीकता स्तर',
    'reset_defaults': 'डिफ़ॉल्ट पर रीसेट करें',
    'reset_settings': 'सेटिंग्स रीसेट करें',
    'settings_reset': 'सेटिंग्स डिफ़ॉल्ट पर रीसेट की गईं',
    'reset_settings_confirm':
        'क्या आप वाकई सभी सेटिंग्स को डिफ़ॉल्ट पर रीसेट करना चाहते हैं?',

    // Map Types
    'normal': 'सामान्य',
    'satellite': 'उपग्रह',
    'terrain': 'भूभाग',
    'hybrid': 'हाइब्रिड',

    // Profile
    'edit_profile': 'प्रोफ़ाइल संपादित करें',
    'update_profile': 'प्रोफ़ाइल अपडेट करें',
    'personal_info': 'व्यक्तिगत जानकारी',
    'name': 'नाम',
    'email': 'ईमेल',
    'phone': 'फ़ोन',
    'location': 'स्थान',
    'statistics': 'सांख्यिकी',
    'plots_saved': 'सहेजे गए भूखंड',
    'measurements': 'माप',
    'profile_updated': 'प्रोफ़ाइल सफलतापूर्वक अपडेट किया गया',

    // Area Result
    'area_calculation_result': 'क्षेत्रफल गणना परिणाम',
    'area_measurements': 'क्षेत्रफल माप',
    'custom_local_unit': 'कस्टम स्थानीय इकाई',
    'unit_name': 'इकाई का नाम',
    'unit_name_hint': 'उदाहरण: बीघा, कठा, गुंठा',
    'conversion_value': 'रूपांतरण मूल्य',
    'value_hint': 'मूल्य',
    'base_unit': 'आधार इकाई',
    'area': 'क्षेत्रफल',
    'unit': 'इकाई',
    'value': 'मूल्य',

    // Saved Plots
    'save_plot': 'भूखंड सहेजें',
    'plot_name': 'भूखंड का नाम',
    'plot_name_hint': 'उदाहरण: उत्तरी खेत',
    'no_saved_plots': 'अभी तक कोई भूखंड सहेजा नहीं गया',
    'no_plots_found': 'कोई भूखंड नहीं मिला',
    'no_plot_with_name': 'इस नाम से कोई भूखंड नहीं',
    'try_different_search': 'किसी अन्य नाम या स्थान से खोजें',
    'start_measuring_land':
        'अपनी भूमि को मापना शुरू करें और भूखंडों को कभी भी सहेजें और एक्सेस करें',
    'search_by_name_location': 'नाम या स्थान से खोजें...',
    'delete_plot': 'भूखंड हटाएं',
    'delete_plot_confirm': 'क्या आप वाकई इस भूखंड को हटाना चाहते हैं?',
    'delete_plot_message': 'यह क्रिया पूर्ववत नहीं की जा सकती।',

    // PDF & Sharing
    'generating_pdf': 'PDF बनाई जा रही है...',
    'pdf_generated': 'PDF सफलतापूर्वक बनाई गई',
    'pdf_shared': 'PDF सफलतापूर्वक साझा की गई',
    'error_generating_pdf': 'PDF बनाने में त्रुटि',
    'error_sharing_pdf': 'PDF साझा करने में त्रुटि',
    'land_measurement_report': 'भूमि माप रिपोर्ट',
    'plot_report_for': 'के लिए भूमि माप रिपोर्ट',
    'share_message': 'यहां BhuMitra से भूमि माप रिपोर्ट है।',
    'generated_by': 'BhuMitra द्वारा उत्पन्न - भूमि क्षेत्र माप ऐप',
    'no_map_data': 'कोई मानचित्र डेटा उपलब्ध नहीं',
    'boundary_coordinates': 'सीमा निर्देशांक',
    'point': 'बिंदु',
    'latitude': 'अक्षांश',
    'longitude': 'देशांतर',
    'date': 'तारीख',
    'land_boundary_map': 'भूमि सीमा मानचित्र',
    'continued_next_page': 'अगले पृष्ठ पर जारी...',

    // Messages & Notifications
    'saving_plot': 'भूखंड सहेजा जा रहा है...',
    'plot_saved': 'भूखंड सफलतापूर्वक सहेजा गया',
    'error_saving_plot': 'भूखंड सहेजने में त्रुटि',
    'custom_unit_saved': 'कस्टम इकाई सहेजी गई',
    'fill_all_fields': 'कृपया सभी फ़ील्ड भरें',
    'enter_valid_number': 'कृपया मान्य संख्या दर्ज करें',
    'minimum_points_required':
        'क्षेत्रफल की गणना के लिए कम से कम 3 बिंदु चिह्नित करें',
    'calculating_area': 'क्षेत्रफल की गणना की जा रही है...',

    // Location & Permissions
    'gps_accuracy': 'GPS सटीकता',
    'high': 'उच्च',
    'location_services_disabled': 'स्थान सेवाएं अक्षम',
    'enable_location_services':
        'GPS सुविधाओं का उपयोग करने के लिए कृपया स्थान सेवाएं सक्षम करें।',
    'location_permission_required': 'स्थान अनुमति आवश्यक',
    'location_permission_message':
        'भूमि सीमाओं को चिह्नित करने के लिए इस ऐप को स्थान अनुमति की आवश्यकता है। कृपया जारी रखने के लिए अनुमति दें।',
    'location_permission_denied':
        'स्थान अनुमति अस्वीकृत। इस सुविधा का उपयोग करने के लिए कृपया इसे सेटिंग्स में सक्षम करें।',

    // Unit Converter
    'from': 'से',
    'to': 'तक',
    'enter_value': 'मूल्य दर्ज करें',
    'result': 'परिणाम',
    'conversion_info': 'रूपांतरण के लिए मूल्य दर्ज करें और इकाइयां चुनें',

    // Help & Support
    'faqs': 'अक्सर पूछे जाने वाले प्रश्न',
    'video_tutorials': 'वीडियो ट्यूटोरियल',
    'contact_support': 'सहायता से संपर्क करें',
    'watch_tutorial': 'ट्यूटोरियल देखें',

    // Auth
    'welcome_to': 'में आपका स्वागत है',
    'login': 'लॉगिन',
    'register': 'पंजीकरण करें',
    'email_address': 'ईमेल पता',
    'password': 'पासवर्ड',
    'confirm_password': 'पासवर्ड की पुष्टि करें',
    'forgot_password': 'पासवर्ड भूल गए?',
    'dont_have_account': 'खाता नहीं है?',
    'already_have_account': 'पहले से खाता है?',
    'sign_in_with_google': 'Google से साइन इन करें',
    'or': 'या',

    // About Screen
    'version': 'संस्करण',
    'features': 'विशेषताएं',
    'about_description':
        'BhuMitra एक व्यापक भूमि माप एप्लिकेशन है जो किसानों और भूमि सर्वेक्षकों को GPS तकनीक का उपयोग करके भूमि क्षेत्रों को सटीक रूप से मापने में मदद करने के लिए डिज़ाइन किया गया है।',
    'gps_measurement': 'GPS-आधारित भूमि माप',
    'save_manage_plots': 'कई भूखंडों को सहेजें और प्रबंधित करें',
    'multi_language': 'बहु-भाषा समर्थन',
    'offline_mode_feature': 'ऑफ़लाइन मोड',
    'dark_mode_feature': 'डार्क मोड',
    'copyright': '© 2024 BhuMitra। सर्वाधिकार सुरक्षित।',

    // Help & Support Screen
    'help_us_improve': 'हमें बेहतर बनाने में मदद करें',
    'view_user_guide': 'पूर्ण उपयोगकर्ता गाइड देखें',
    'how_to_use_bhumitra': 'BhuMitra का उपयोग कैसे करें',
    'watch_step_by_step':
        'भूमि को सटीक रूप से मापने के लिए हमारी चरण-दर-चरण मार्गदर्शिका देखें',

    // FAQ Questions
    'faq_mark_boundaries_q': 'भूमि सीमाओं को कैसे चिह्नित करें?',
    'faq_mark_boundaries_a':
        'आप दो मोड का उपयोग करके सीमाओं को चिह्नित कर सकते हैं:\n\n• पिन मोड: प्रत्येक कोने पर मार्कर रखने के लिए मानचित्र पर टैप करें\n• वॉक मोड: GPS ट्रैकिंग के साथ अपनी भूमि के चारों ओर चलें',
    'faq_area_units_q': 'क्षेत्रफल इकाइयों को समझना',
    'faq_area_units_a':
        'BhuMitra कई इकाइयों का समर्थन करता है:\n\n• वर्ग फुट (sq ft)\n• वर्ग मीटर (sq m)\n• वर्ग गज (sq yd)\n• एकड़\n• हेक्टेयर\n\nआप बीघा, कठा, गुंठा जैसी कस्टम स्थानीय इकाइयों को भी परिभाषित कर सकते हैं।',
    'faq_save_measurements_q': 'माप कैसे सहेजें?',
    'faq_save_measurements_a':
        'क्षेत्रफल की गणना के बाद:\n\n1. "भूखंड सहेजें" बटन पर क्लिक करें\n2. अपने भूखंड के लिए एक नाम दर्ज करें\n3. होम स्क्रीन से सहेजे गए भूखंडों तक पहुंचें\n\nसभी माप आपके डिवाइस पर स्थानीय रूप से सहेजे जाते हैं।',
    'faq_gps_accuracy_q': 'GPS सटीकता युक्तियाँ',
    'faq_gps_accuracy_a':
        'बेहतर GPS सटीकता के लिए:\n\n• सुनिश्चित करें कि स्थान सेवाएं सक्षम हैं\n• ऐप का उपयोग खुले क्षेत्रों में करें\n• सीमा के चारों ओर धीरे-धीरे चलें\n• ऊंची इमारतों या घने पेड़ों से बचें\n• GPS सिग्नल के स्थिर होने की प्रतीक्षा करें',
    'faq_custom_units_q': 'कस्टम स्थानीय इकाइयों का उपयोग',
    'faq_custom_units_a':
        'कस्टम इकाइयों को परिभाषित करने के लिए:\n\n1. माप के बाद परिणाम स्क्रीन पर जाएं\n2. "कस्टम स्थानीय इकाई" अनुभाग खोजें\n3. अपनी इकाई का नाम दर्ज करें (उदा., बीघा)\n4. रूपांतरण कारक दर्ज करें\n5. आधार इकाई चुनें\n6. गणना करें पर क्लिक करें',
    'faq_offline_mode_q': 'ऑफ़लाइन मोड',
    'faq_offline_mode_a':
        'BhuMitra ऑफ़लाइन काम कर सकता है:\n\n• सेटिंग्स में ऑफ़लाइन मोड सक्षम करें\n• मानचित्र ऑफ़लाइन उपयोग के लिए कैश किए जाएंगे\n• सभी माप इंटरनेट के बिना काम करते हैं\n• ऑनलाइन होने पर डेटा सिंक होता है',

    // User Guide Screen
    'user_guide': 'उपयोगकर्ता गाइड',
    'introduction': 'परिचय',
    'introduction_desc':
        'BhuMitra एक शक्तिशाली भूमि माप उपकरण है जो GPS तकनीक का उपयोग करके भूमि क्षेत्रों को सटीक रूप से मापने में आपकी मदद करता है। चाहे आप किसान हों, सर्वेक्षक हों, या भूमि मालिक हों, यह ऐप भूमि मापना सरल और सटीक बनाता है।',
    'getting_started': 'शुरू करना',
    'getting_started_desc':
        'मापना शुरू करने से पहले, सुनिश्चित करें कि आपके डिवाइस में स्थान सेवाएं सक्षम हैं और बेहतर GPS सटीकता के लिए आपके पास आकाश का स्पष्ट दृश्य है। ऐप ऊंची इमारतों से दूर खुले क्षेत्रों में सबसे अच्छा काम करता है।',
    'step_by_step_guide': 'चरण-दर-चरण मार्गदर्शिका',
    'step1_title': 'ऐप खोलें',
    'step1_desc':
        'BhuMitra लॉन्च करें और संकेत मिलने पर स्थान अनुमतियां दें। GPS सिग्नल के स्थिर होने की प्रतीक्षा करें।',
    'step2_title': 'मापना शुरू करें',
    'step2_desc':
        'होम स्क्रीन से "भूमि मापें" पर टैप करें। पिन मोड (मानचित्र पर टैप करें) या वॉक मोड (सीमा के चारों ओर चलें) के बीच चुनें।',
    'step3_title': 'सीमाएं चिह्नित करें',
    'step3_desc':
        'अपनी भूमि के चारों ओर कम से कम 3 बिंदु चिह्नित करें। वॉक मोड में, परिधि के चारों ओर धीरे-धीरे चलें। पिन मोड में, मानचित्र पर प्रत्येक कोने पर टैप करें।',
    'step4_title': 'क्षेत्रफल की गणना करें',
    'step4_desc':
        'एक बार जब आप सभी बिंदुओं को चिह्नित कर लें, तो क्षेत्रफल की गणना करने के लिए "समाप्त करें" पर टैप करें। ऐप कई इकाइयों में परिणाम दिखाएगा।',
    'step5_title': 'सहेजें और साझा करें',
    'step5_desc':
        'भविष्य के संदर्भ के लिए अपने माप को एक नाम के साथ सहेजें। आप PDF रिपोर्ट भी बना और साझा कर सकते हैं।',
    'tips_best_practices': 'सुझाव और सर्वोत्तम प्रथाएं',
    'tips_desc':
        '• सर्वोत्तम GPS सटीकता के लिए हमेशा खुले क्षेत्रों में मापें\n• वॉक मोड में धीरे और स्थिर रूप से चलें\n• पिन मोड में सटीक कोनों पर बिंदु चिह्नित करें\n• गणना के तुरंत बाद माप सहेजें\n• बीघा या कठा जैसे स्थानीय मापों के लिए कस्टम इकाइयों का उपयोग करें',
    'troubleshooting': 'समस्या निवारण',
    'troubleshooting_desc':
        'GPS काम नहीं कर रहा? जांचें कि डिवाइस सेटिंग्स में स्थान सेवाएं सक्षम हैं या नहीं।\n\nगलत माप? सुनिश्चित करें कि आप खुले क्षेत्र में हैं और GPS सिग्नल मजबूत है।\n\nऐप क्रैश हो रहा है? ऐप को पुनः आरंभ करने या ऐप कैश साफ़ करने का प्रयास करें।',

    // Connectivity
    'no_internet_connection': 'कोई इंटरनेट कनेक्शन नहीं',
    'internet_connected': 'वापस ऑनलाइन',
  },
};
